### PR TITLE
Added direct and indirect write methods to DSv1

### PR DESCRIPTION
**Pull request by davidrabinowitz**

### CODE REVIEW

**Review by VinayLondhe14 — COMMENTED** [review]
Don't we need to run `DataSourceV1WriteIntegrationTest` with all 3 modes - DIRECT, INDIRECT and OLD_INDIRECT to ensure all 3 modes are working in DSv1?

**Comment by davidrabinowitz** [comment]
> Don't we need to run `DataSourceV1WriteIntegrationTest` with all 3 modes - DIRECT, INDIRECT and OLD_INDIRECT to ensure all 3 modes are working in DSv1?

Yes, in an upcoming PR. As this is a large PR already, I want to handle any issues with the new implementation separately.

**Review by VinayLondhe14 — APPROVED** [review]

**Pull request merged**
