### PR TITLE
Fixing premature client closing in certain cases

### PR DESCRIPTION
**Pull request by davidrabinowitz**
This PR reverts some of the code from PR #832

### CODE REVIEW

**Review by emkornfield — COMMENTED** [review]
What are the plans for testing this to make sure we don't have a regression.  Can we still leak connections?

**Comment by davidrabinowitz** [comment]
No, we are actually closing all clients using shutdown hooks, see [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/c8ed54702e27a3dd591f265ae30af0072d3e2ada/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java#L75)

**Review by suryasoma — APPROVED** [review]

**Pull request merged**
