### PR TITLE
Add flags to support automated builds.

### PR DESCRIPTION
**Pull request by askdre**
Remove the need for tty during singing so that gpg plugin can run from a headless script.
Add flag to allow splitting when the staging repo gets built and when it gets uploaded.

### CODE REVIEW

**Review by davidrabinowitz — APPROVED** [review]

**Review by davidrabinowitz — CHANGES_REQUESTED** [review]
Please fix XML structure (see cloud build for details)

**Comment by askdre** [comment]
Fixed.

**Comment by askdre** [comment]
Closing this pull request in favor of a simplified topic branch PR.

**Pull request closed without merging**
