### PR TITLE
Make background processing classes more robust to errors

### PR DESCRIPTION
**Pull request by emkornfield**
If a throwable error is made (for instance ZSTD error) previously this would result in a hang because it wasn't caught and handled in the submitted task.  This PR make changes to catch throwables everyplace necessary to avoid issues like this in the future.

### CODE REVIEW

**Review by davidrabinowitz — CHANGES_REQUESTED** [review]
Which Errors does ZSTD throws? Can we make sure that we are not swallowing `Error`s needlessly (such as OOM)?

**Comment by emkornfield** [comment]
> Which Errors does ZSTD throws? Can we make sure that we are not swallowing Errors needlessly (such as OOM)?

Note this change doesn't swallow the errors.  It makes sure they are all caught and surfaced to user facing threads.  The issue before is a background thread would die with one of these exceptions, and user facing threads would block endlessly waiting for data.

**Review by davidrabinowitz — APPROVED** [review]

**Pull request merged**
