### PR TITLE
Add row and bytes statistics collection to tracer

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Review by davidrabinowitz — APPROVED** [review]

**Review by davidrabinowitz — CHANGES_REQUESTED** [review]
The unit test had failed:
```
[error] /workspace/connector/src/main/java/com/google/cloud/bigquery/connector/common/LoggingBigQueryStorageReadRowsTracer.java:100: toSeconds() has private access in java.time.Duration
[error]     return metric / time.toSeconds();
[error] /workspace/connector/src/main/java/com/google/cloud/bigquery/connector/common/LoggingBigQueryStorageReadRowsTracer.java:100: bad operand types for binary operator '/'
[error]   first type:  long
[error]   second type: java.math.BigDecimal
[error]     return metric / time.toSeconds();
```

**Comment by emkornfield** [comment]
Sorry, it looks like the API change between different versions, I think new commit should fix this.

**Comment by emkornfield** [comment]
@davidrabinowitz I can't seem to access the gcbrun logs, could you grant access or let me know what issue they are still running into?

**Comment by emkornfield** [comment]
@davidrabinowitz looks like tests are passing now.  There was one unrelated failure I think because of server side changes.

**Review by anoopj — APPROVED** [review]
LGTM

**Review by davidrabinowitz — APPROVED** [review]

**Pull request merged**
