### PR TITLE
fix read, write issues with Timestamp

### PR DESCRIPTION
**Pull request by vishalkarve15**
This PR fixes 2 things:
- an overflow error in SparkBigQueryUtil that caused off-by-one errors
- error while reading a BQ Timestamp field in non-GMT local timezone

### CODE REVIEW

**Comment by vishalkarve15** [comment]
This only works for Spark 3 DSv2. Also works for Scala 2.13 DSv1 since it compiles against Spark 3.2

**Review by isha97 — APPROVED** [review]

**Pull request merged**
