### PR TITLE
update readme with possible partitions type

### PR DESCRIPTION
**Pull request by sobelek**
Updated readme from issue #512 
Also I noticed that readme is missing information added in #267 so I updated it as well

### CODE REVIEW

**Comment by davidrabinowitz** [comment]
Thanks @sobelek ! Can you please [sign the CLA](https://cla.developers.google.com/) so I can merge this?

**Comment by sobelek** [comment]
Oh, I forgot about CLA. It has to go through coporate so may take a while but I am on it :)

**Comment by sobelek** [comment]
It took a while 😄 
Can you @davidrabinowitz please rescan CLA check?

**Comment by sobelek** [comment]
@davidrabinowitz 
We had some miss understanding of how signing process works but it should be good to go now. I can see signed CLA for @allegro.pl email here: https://cla.developers.google.com/clas

Could you please re-ran the check?

**Pull request merged**
