### PR TITLE
feat: add support for writing JSON columns through Avro indirect write

### LINKED ISSUE #637: Support for JSON type (Public Preview)
Hi, It would be great if we could add the support for the JSON type (Public Preview). I've tested it recently with Spark connector and it's not working. Thanks!

https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data

### PR DESCRIPTION
**Pull request by jonathan-ostrander**
Closes #637

BigQuery supports writing JSON columns through the Avro string type as long as there is a `sqlType` type annotation of `JSON` in the schema: https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#extract_json_data_from_avro_data. This change reads the metadata of `StructField`s with a string type when converting from Spark SQL schema to Avro and if it contains the `JSON` for the `sqlType` key then it will include the type annotation.

### CODE REVIEW

**Comment by jonathan-ostrander** [comment]
@sonatype-lift hasn't signed the CLA 🤔

**Comment by davidrabinowitz** [comment]
@jonathan-ostrander can you please sign the CLA so we can review the PR?

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz I did before opening the PR and CLA passes now. It failed before because I committed a change that the sonatype-lift bot suggested and then the CLA check failed because the bot was a co-author.

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz just pinging to get the CI/CD running

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz sorry to be a bother but pinging again for the /gcbrun now that the map lookup and unit test fixture are fixed

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz not sure how to work around the code coverage stuff. I added a test case for my change. I can write a unit test specifically for checking that the metadata is passed around but that seems redundant.

**Comment by jonathan-ostrander** [comment]
@davidrabinowitz sorry again for all the pings

My org is planning on backfilling a lot of data with JSON blobs and it'd be helpful to have this change (rather than writing to Avro ourselves or loading the JSON data in to a different table as a string and then copy it to the destination table as JSON).

**Review by davidrabinowitz — APPROVED** [review]

**Pull request merged**
