### PR TITLE
Added ability to set table labels while writing to a BigQuery table

### PR DESCRIPTION
**Pull request by VinayLondhe14**

### CODE REVIEW

**Review by davidrabinowitz — APPROVED** [review]

**Comment by dmedora** [comment]
Hi @VinayLondhe14, just wanted to note that although this is documented in `README-template.md`, it is not actually in `README.md` and so is not easily discovered.

**Comment by davidrabinowitz** [comment]
Thanks for the comment @dmedora, `README-template.md` is used to document unreleased features, it is copied to `README.md` on release

**Pull request merged**
