### PR TITLE
Add Spark 3.3 Pushdown dependency in Scala 2.12

### PR DESCRIPTION
**Pull request by isha97**

### CODE REVIEW

**Review by davidrabinowitz — CHANGES_REQUESTED** [review]
Please apply to spark-bigquery_2.13 as well

**Review by davidrabinowitz — APPROVED** [review]

**Comment by mina-asham** [comment]
Do we also need to add 3.4 (for dataproc serverless 2.1) and 3.5 (for dataproc 2.2 and dataproc serverless 2.2)?

**Comment by sid-habu** [comment]
Is the `spark-3.4-bigquery-pushdown` jar available on Maven?

**Pull request merged**
